ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

= Innovar desde la compra en el Ayuntamiento de Barcelona

== Antecedentes

Desde Europa (Directiva 2014/24/ UE) se pro-mueve la contratación pública estratégica, la que asocia el concepto de eficiencia en el gasto público con la promoción de objetivos sociales comunes europeos fijados en la comunicación de la Comisión Europea, Europa 2020, Una estrategia para un crecimiento sostenible, inteligente e Integrador.

En esta línea, el último mes de abril, el Ayuntamiento de Barcelona aprobó un decreto de alcaldía de contratación pública sostenible (S1/D/2017-1271, 24 de abril), que manifestaba que “El Ayuntamiento de Barcelona impulsa la contratación pública sostenible que integra, en la causa y el objeto del contrato público municipal, medidas sociales, ambientales, éticas y de innovación, garantizando los derechos laborales, sociales y ciudadanos de las personas que ejecuten el contrato público y de las personas destinatarias o usuarias del mismo, que impulsen una economía local circular y sostenible y que promuevan la actividad económica de las medianas, pequeñas y microempresas locales y, singularmente, de las empresas sociales “.

En ese decreto se aprobaban también las guías de contratación pública social y contratación pública ambiental que han sido la pauta orientadora de la contratación pública sostenible del Ayuntamiento de Barcelona.

Esta guía de contratación pública innovadora quiere complementar las pautas ya aprobadas introduciendo la innovación ligada al desarrollo de la sostenibilidad económica, social y ambiental, y como elemento multiplicador que ayuda a crear empleo y crecimiento económico, potencia los valores sociales y ambientales a la vez que da apoyo a las empresas innovadoras que resuelven los retos de la ciudadanía.

Esta guía se ha debatido internamente dentro de la organización municipal y con posterior diálogo con entidades ciudadanas representativas de las actividades económicas, sociales y vecinales, en el seno de la “Mesa de Contratación Pública” constituida por Resolución de la Alcaldía de 21 de octubre de 2016 como espacio de diálogo ciudadano en contratación pública.

== Qué es la contratación pública para la innovación (CPI)?

La contratación pública para la innovación es una nueva manera de contratar y de dialogar con el mercado para responder a las necesidades que no encuentran soluciones en los procesos ordinarios.

Se trata de utilizar el dinero público para comprar lo que necesitamos, intentando hacer el gasto con estrategia para alcanzar nuestros objetivos de mejorar y satisfacer las necesidades de la ciudadanía potenciando la innovación y la sostenibilidad.

Este nuevo enfoque de las compras públicas se postula como una herramienta fundamental del Ayuntamiento para obtener soluciones que se ajusten mucho más a las demandas reales de la sociedad y para ayudar a las empresas a ser más competitivas.
Queremos estimular la creación de nuevos mercados locales, nuevos productos, nuevos métodos de producción o nuevas maneras de organización o suministro y prestación de servicios.

¿Y cómo lo haremos? La CPI empieza, en la práctica, con una definición abierta de retos y necesidades a solucionar y ofrece en el mercado la posibilidad de explicar cómo resolver el problema, ya sea con soluciones existentes o no, pero que dispongan de una buena relación calidad-precio y tengan en cuenta el ciclo de vida en el cálculo y la determinación de los costes.
Esta práctica posiciona al Ayuntamiento con un rol más allá del comprador i pasa a ser socio en la resolución del reto identificado.

Tenemos que pasar de una compra pública muy detallada en los pliegos técnicos y a menudo adjudicada con criterios del mejor precio, a una compra que trabaja por definición de retos y soluciones sostenibles innovadoras, a menudo con la implicación de multiplicidad de actores.
Este nuevo planteamiento permite la entrada de ideas, de soluciones innovadoras que aportan eficiencia.
Un ejemplo sencillo sería pasar de comprar farolas a comprar luz, o pasar de comprar bolígrafos a horas de escritura.

El Ayuntamiento, pues, posiciona como tractor de innovación del mercado y banco de pruebas de sus compras al adquirir los resultados de la investigación y no subvencionar pruebas piloto que a menudo encuentran dificultades para escalar el impacto.

Elementos como el riesgo, la eficiencia de costes, la colaboración entre agentes y asegurar que se comparten los beneficios son elementos clave en una CPI.

.Beneficios principales que aporta la CPI:
[TIP]
====
* *PARA LA CIUDADANÍA.*
Mejora de los servicios públicos mediante la incorporación de bienes o servicios innovadores que sirven mejor y más eficientemente a las
necesidades de los ciudadanos y las ciudadanas.

* *PARA LA INDUSTRIA.*
Fomenta las empresas y las PYMES innovadoras que promueven los valores del Ayuntamiento en materia
social, ambiental y tecnológico, impulsando el desarrollo y la internacionalización, ya que aprovechan el mercado público local como primer
cliente de referencia.

* *PARA LA ADMINISTRACIÓN.*
Promueve un cambio cultural dentro de la misma Administración, acercándola a prácticas más innovadoras y alcanzando eficiencia económica y técnica.
====

== La compra pública con visión estratégica

La estrategia Europa 2020 para un crecimiento inteligente, sostenible e integrador apuesta por una economía basada en el conocimiento y la innovación, con un uso más eficaz de los recursos y que sea más competitiva, con un alto nivel de empleo y buscando cohesión social y territorial.
La directiva 2014/24 señala en su considerando segundo que la contratación pública tiene un papel clave en la Estrategia Europa 2020.

TIP: Bajo la iniciativa europea Horizonte 2020 se habilitan fondos para que el sector público y privado alcance los objetivos de crecimiento sostenible y de innovación.
En el periodo 2014-2020, la inversión prevista por la UE es de 70.200 millones de euros.

Y eso es así porque el gasto de las administraciones representa el 20% del PIB europeo, hecho que convierte a los gobiernos en un agente económico relevante con una gran capacidad de influencia en el mercado.

De hecho, la Unión Europea promueve activamente la compra pública para la innovación (CPI) como instrumento para hacer política pública.
Además de ofrecer fondo para financiarla, establece nuevos procedimientos que apoyan a la innovación e invita a los sectores compradores a trabajar de manera diferente con una visión más estratégica.

Y es que la CPI pretende salvar el vacío existente entre las necesidades sociales y ciudadanas, los procesos administrativos y el mercado.

Hasta ahora, los gobiernos han subvencionado la industria y el ámbito de la investigación para el desarrollo de nuevas tecnologías y sus aplicaciones, con proyectos que a menudo no pasan de la fase piloto y provocan un cierto desencanto en la industria, que pierde la confianza en el sector público como motor de innovación.

Con el nuevo enfoque de la compra pública se quiere acercar la innovación al mercado y hacer que el sector público se convierta en cliente y beneficiario de soluciones sostenibles e innovadoras más ajustadas a sus necesidades.

Pero no hablamos solo de teoría, sino que existen buenos ejemplos en sectores como las infraestructuras y la sanidad, en los que se empieza a disponer de resultados objetivos de la aplicación de esta nueva manera de comprar, en los que la capacidad de demanda del sector público está siendo el instrumento esencial para desarrollar nuevos mercados y satisfacer las necesidades sociales cada vez más exigentes y complejas.

== Qué papel tendrá Barcelona?

En 2014 Barcelona fue nombrada Capital Europea de la Innovación.
Este mismo año, la Unión Europea aprobó las nuevas Directivas de contratación pública.
Desde Europa se nos pide que compremos soluciones innovadoras para resolver retos que, sin las últimas tecnologías e investigaciones, no encontrarían una respuesta eficaz a nuestros problemas sociales y ambientales del siglo XXI.

TIP: La investigación y la innovación, incluidas la innovación ecológica y la innovación social, se encuentran entre los motores principales del crecimiento futuro y ocupan un lugar central en la estrategia Europa

Sin embargo, la visión de la innovación de la Comisión Europea se entiende como un proceso de desarrollo lineal que parte de la idea, pasando por diferentes estadios de maduración apoyados en centros tecnológicos hasta llegar al mercado.

Otras voces se alzan a Europa con visiones más amplías observando que el nuevo enfoque de la compra pública con visión estratégica de las administraciones genera innovación por sí misma.
La innovación no se encuentra necesariamente como resultado final de un proceso de investigación desde la idea, sino que surge de manera más amplia desde el conjunto de actores, que, traccionados por la resolución de los retos planteados desde la Administración (también denominada _demanda sofisticada_), generan innovación.
Es toda la sociedad la que crea innovación en el proceso de buscar soluciones a los retos planteados.
Barcelona ve la innovación como un fin en sí mismo y, al mismo tiempo, como un potenciador de soluciones más sociales y más ambientales.

El consistorio quiere aprovechar sus conocimientos y los existentes en el mercado para ayudar a resolver los retos de ciudad con nuevas soluciones.
Esto requiere nuevas habilidades para las personas encargadas de gestionar el presupuesto público, nuevas habilidades en el personal técnico municipal, nuevos mecanismos legales de compra, nuevas metodologías más ágiles en el desarrollo de soluciones para el ciudadano.
Y también nuevas maneras de explicar al mercado y a la ciudadanía cuáles son los retos de la ciudad y su ciudadanía, facilitando la investigación y desarrollo compartido y colaborativo de soluciones.

Hay que poner la innovación al servicio de las personas y del bien común.
El sector público se convierte en un promotor de la empresa innovadora, innovando él mismo en su manera de relacionarse con el mercado y en sus procedimientos de compra.

El peso del criterio precio imperante hasta ahora tiene que pasar a un segundo lugar, y mediante la programación, comunicación en el mercado de las futuras licitaciones, acontecimientos y diálogos con el mercado, se tienen que diseñar fórmulas que permitan premiar la inversión en R+D+i por parte de las pymes cuando esté destinada a la creación de crecimiento y empleo de calidad, o bien a proteger nuestros valores sociales y ambientales. Generaremos, así, una confianza del mercado con el Ayuntamiento generador de valor y comprador, creando una masa crítica local en el sector público y privado que aprende a comprar, vender y sobretodo colaborar de una manera diferente, promoviendo soluciones innovadoras para el bien común.

TIP: Barcelona apuesta por la innovación en un sentido amplio, y ha adoptado utilizar su potencial de compra para estimular la innovación dirigida a resolver los retos de la vida en la ciudad y a amplificar el impacto de sus políticas sociales y ambientales.

== Podemos promover la innovación en las compras regulares?

La respuesta es sí, introduciendo en los tratos la posibilidad de variantes o medidas que fomenten la innovación y modificando el proceso que	de compra (planificación, consultas previas...).

[TIP]
====
* Barcelona propone una definición amplia de promoción de la innovación en su estrategia.

* Entiende la compra pública para la innovación (CPI) como la compra pública que aprovecha las soluciones innovadoras (productos, tecnologías, procesos) que surgen en el proceso de compra para fomentar un impacto mayor en el crecimiento sostenible e integrador de la sociedad.

* Barcelona también promueve, con los mismos objetivos, la inclusión de la innovación en sus compras regulares.
====

.Ya tenemos experiencia
[TIP]
====
El BCN Open Challenge hizo que el mismo Ayuntamiento se convirtiera en cliente y comprador de soluciones innovadoras, por primera vez, cerrando el círculo de los ‘urban labs’ y sumando la financiación y el vector de compromiso de contratación pública en el programa de resolución de retos.
Pero el BCN Open Challenge también nació con la voluntad de llegar a cualquier persona, profesional, empresa o colectivo que dispusiera de una idea innovadora aplicable, independientemente de su naturaleza o experiencia, asegurando así oportunidades para todo el mundo con capacidad de innovar.

Es por este motivo que la naturaleza de las empresas seleccionadas es muy diversa, cosa que nos satisface especialmente, ya que tenemos como ganadoras a pequeñas y medianas empresas ya constituidas, pero también a nuevas empresas creadas expresamente para presentarse a este llamamiento, una unión temporal de empresas (UTE) e incluso un centro tecnológico, lo que demuestra la capacidad de este programa 3 para fomentar nuevas formas empresariales innovadoras y la colaboración entre ellas.

_http://www.barcelonactiva.cat/barcelonactiva/es/novedades-y-prensa/novetats/2014/05/09/noticia112879.jsp_
====
//enllaç trencat

== Para quién es esta guía?

Esta guía es:

* *Para el conjunto de personas que trabajan en el Ayuntamiento de Barcelona, responsables de área y órganos municipales, personas encargadas de compra pública y personal técnico municipal.*
* *Para el sector privado, empresas y entidades  proveedoras del Ayuntamiento, presentes y futuras.*
* *Para la ciudadanía, ya que la transparencia en toda la contratación pública estratégica y la innovación serán el hilo conductor de todas las iniciativas.*

TLa guía orienta a quien la lee a considerar la innovación como elemento fundamental indisociable y potenciador de las compras sostenibles, tal como se recoge en la Ley de Contratos del Sector Público y en el Decreto de Alcaldía de contratación pública sostenible (S1/D/2017-1271 de 24 de abril), en el cual se establece, en su primer artículo, la voluntad de impulsar medidas sociales, ambientales y de innovación.
El decreto promueve la garantía de los derechos laborales, sociales y ciudadanos de las personas que ejecuten el contrato público y de las personas destinatarias del mismo, e impulsa acciones para la economía circular y la mejora de la actividad económica de las pequeñas y medianas empresas.

.Artículo 6. La innovación
[TIP]
====
*6.1. La directiva 24/2014, de contratación pública, define en su artículo 2.1.22 la innovación como “la introducción de un producto, servicio o proceso nuevo o significativamente mejorado, que incluye, aunque no se limita a ellos, los procesos de producción, edificación o construcción, un nuevo método de comercialización o un nuevo método de organización de prácticas empresariales, la organización del puesto de trabajo o las relaciones exteriores, entre otros, con el objetivo de ayudar a resolver desafíos de la sociedad o de apoyar la Estrategia Europa 2020 para un crecimiento inteligente, sostenible e integrador...”.*

*6.2. El Ayuntamiento de Barcelona impulsará procesos de compra pública de innovación con el fin de promover la investigación, el desarrollo de ideas y nuevas tecnologías que permitan la realización de sus actividades a favor de la ciudadanía cuando estas no estén disponibles en el mercado.*

*6.3. En la adquisición de obras, bienes y servicios se incorporarán, de manera generalizada, medidas de potenciación de la innovación a partir de la fijación de prescripciones técnicas de carácter funcional, criterios de adjudicación que potencien las mejoras articuladas como propuestas de innovación o cualquier otra medida que favorezca una innovación relacionada con el desarrollo de la sostenibilidad económica, social y ambiental.*

_Decreto de Alcaldía de contratación pública sostenible (S1/D/2017-1271 de 24 de abril)_
====
