ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

= Cómo hacerlo realidad. Principios y procedimientos

== Cómo empezamos?

La contratación pública para la innovación no es un procedimiento de contratación nuevo, es una nueva manera de contratar de forma colaborativa para responder a necesidades que no encuentran solución en el mercado.

Esta manera de contratar con una visión estratégica nos lleva a una planificación más esmerada de nuestra acción de compra.
Es una nueva cultura.
Tenemos que reflexionar con una visión holística sobre todo el proceso, desde la detección de la necesidad, la consulta en el mercado o la preparación administrativa, hasta la ejecución; pero también observando el seguimiento y la evaluación de los resultados.
Tenemos que verificar en qué grado satisfacemos finalmente nuestras necesidades y podemos escalar las soluciones tal y como habíamos planificado.

.Algunas acciones a emprender

[TIP]
====
* Formación
* Planificación, colaboración y confianza
* Creación de redes
* Provisión de financiación
* Análisis de riesgos
* ... y “más formación”...
====

Cada compra tendrá que ser analizada caso por caso.
¿Qué necesidad tenemos que cubrir?
¿Existe ya la solución en el mercado o hay que inventarla?
¿Qué pasaría si, existiendo, todavía no estuviera comercializada...?
¿Nuestro proveedor se puede convertir en nuestro socio?

Por eso tenemos que estructurar nuestras compras en cuatro pilares.

[cols="^,^,^,^", , grid=cols, valign=top, options="header",]
|===
|Pilar I  |Pilar II |Pilar III |Pilar IV
|Detectar las necesidades
|Involucrar a los diferentes actores
|Iniciar la compra
|Seguir y evaluar
|Identificación del reto y de la compra para la  innovación con un impacto claro y escalable.
|Identificación de los actores, preparación de reuniones de trabajo, aviso previo de licitación,
consultas en el mercado y aseguramiento de la igual
dad de trato.
|Elección del procedimiento, redacción de los pliegos, establecimiento de los criterios de selección, gestión del riesgo, procesos de financiación...
Valorar compras conjuntas
|Seguimiento de la ejecución del contrato (el verdadero cambio)
Evaluación de la CPI y resumen de lecciones aprendidas
|===

Veámoslo paso a paso...

== PILAR I: Detectar las necesidades

Todas las personas nos encontramos ante multitudes de necesidades y problemas para resolver.
Tendríamos que definir con amplitud de miras los objetivos a alcanzar mediante el contrato público: detectar vuestros objetivos, vuestras necesidades y vuestros retos.
Hay que aplicar un sistema e ir construyendo un catálogo e inventario de estas necesidades.
Nos tenemos que plantear, una vez formuladas las necesidades, si están orientadas con los objetivos de la ciudad y la ciudadanía, si pueden ser solucionadas por procesos sencillos o tenemos que aplicar métodos complejos.
En definitiva, tenemos que construir una categorización y orden de prioridades.

*Empieza pronto y decide si estás ante una CPI*

El hecho de querer promover la innovación no tiene que llevarnos a crear falsas necesidades.
La detección de auténticas necesidades será el fruto de sesiones conjuntas de trabajo con los actores que trabajan con el bien o el servicio a comprar, con el personal técnico, las personas usuarias, los proveedores.
Estas sesiones se plantean como una lista de deseos a alcanzar.
Por eso, antes de hacer el pliego hay que averiguar si la solución existe o no y si necesita o no el desarrollo de pruebas piloto.

*Ejemplo:*

En el marco de proyectos CPI financiados bajo el programa FEDER RIS3cat, el reto que se está planteando el Ayuntamiento es la investigación de soluciones en pavimentos que reduzcan el efecto de isla de calor, la generación de ruido y la reducción de contaminación atmosférica.

De las sesiones internas de trabajo se ha entendido que los pavimentos urbanos tendrían que contribuir al hecho de que la ciudad fuera más confortable para sus habitantes, alcanzando un carácter más natural con características parecidas a la piel o a la ropa, y ser resistentes a las solicitaciones externas, permitiendo la transpirabilidad, el drenaje y el mantenimiento de una temperatura confortable.
La piel tiene terminaciones nerviosas (sensores) que permiten sentir frío o calor, o detectar patologías o daños con un cambio de color y otros (erupciones, cortes, etc.).
Estas han sido las bases para iniciar una consulta en el mercado y determinar si existen soluciones que den respuesta a esta necesidad.

.*Necesidades: la clave*
[TIP]
Una evaluación de necesidades debe tener en cuenta tanto las necesidades actuales como las futuras, y examinar la capacidad de la organización para asumir las soluciones potenciales.
Una evaluación de las necesidades genera una mejor base de consulta abierta al mercado, ya que proporciona datos esenciales para las entidades proveedoras e identifica cualquier tipo de laguna.

== PILAR II: Involucrar a los diferentes actores

Una vez hemos formulado nuestro reto, es fundamental contar con la ayuda de profesionales y un servicio de asesorías con conocimiento actualizado del mercado, y asegurarse una imagen completa de los últimos avances.
Para ello se tiene que consultar una amplia variedad de fuentes y trabajar con equipos multidisciplinares.
Podemos recurrir a otras gerencias o áreas de la misma organización, a congresos locales o internacionales, universidades, agencias de innovación y/o redes europeas, asociaciones empresariales, sindicales, sociales, vecinales, etc.
Tenemos que decidir qué información es necesaria recoger y compartir y a qué operadores del mercado nos tenemos que dirigir.

*Consultas en el mercado*

En el proceso de estructuración de nuestra compra también podemos formalizar una consulta en el mercado.
El lanzamiento de la consulta preliminar del mercado nos permitirá conocer la oferta existente y, al mismo tiempo, nos posibilitará implicar anticipadamente el mercado.

Estas consultas no son vinculantes para la Administración y, en ningún caso, no tienen que privilegiar a unos actores frente a otros, de manera que toda la información durante la consulta tiene que ser pública, se tienen que proteger los derechos de propiedad industrial e intelectual de las entidades proveedoras, y se tiene que informar de los resultados.
Este diálogo puede iniciarse con un anuncio previo de licitación.
Los pasos esenciales a seguir son los siguientes:

* Decidir qué información es necesario recoger y compartir, y a qué operadores de mercado hay que dirigirse.
* Escoger el mejor formato para la consulta y preparar los recursos materiales y humanos necesarios.
* Desarrollar la consulta conservando un archivo del desarrollo y asegurando la igualdad de trato.

*Evaluación de la sostenibilidad y la innovación en los resultados de la consulta en el mercado*

El Ayuntamiento está elaborando una metodología de apoyo para facilitar la evaluación de las ideas y las soluciones que nos lleguen de la consulta al mercado.
La metodología que se utiliza es general para cualquier idea o solución y permitirá priorizarlas según el grado de innovación y sostenibilidad que aporten.

El método tiene dos fases: en una primera, se evalúa la innovación que aporta la idea en sí misma y atendiendo a las circunstancias del entorno, de la entidad proponente y la alineación que la idea tiene con los objetivos del Ayuntamiento de Barcelona.

En una segunda fase hay que analizar la sostenibilidad de la idea a partir de analizar cómo es de real, viable y social su implementación.

.Caso SPEA EINDHOVEN - La palabra clave es ‘colaboración’
[TIP]
El ayuntamiento de Eindhoven apuesta por la construcción sostenible con un enfoque más integrado y holístico, un enfoque que haga lógico que las diferentes partes involucradas se esfuercen para la calidad a largo plazo y satisfagan las necesidades de todas las partes interesadas.
Además, las inversiones en innovación y calidad requieren un plazo más largo para obtener un rendimiento suficiente de la inversión gracias a las economías de escala y la cooperación.
El horizonte del proyecto es, por lo tanto, 2045.
La metodología de “Paso Natural” se aplica para mejorar la sostenibilidad de los edificios
_(http://www.eindhoven.nl/artikelen/Duurzaamheid-volgens-The-Natural-Step.htm)_
//enllaç trencat

== PILAR III: Iniciar la compra

*Elección del procedimiento: Los factores a considerar*

El primer paso para escoger el procedimiento es formularse las preguntas siguientes:
¿necesitaré una I+D+i?
¿Hay la solución pero no a escala comercial?
¿Disponemos de suficiente información para redactar las prescripciones técnicas?
Se recomienda un uso flexible de los procedimientos de contratación y una decisión caso por caso.

De hecho, podemos solucionar algunos de nuestros retos adquiriendo innovación mediante la introducción de *cláusulas o medidas de innovación en nuestras compras regulares*.

Si entendemos que hay que contratar exclusivamente servicios de I+D para desarrollar una solución que no está disponible en el merca-do, haremos uso de la *Compra pública pre-comercial (CPP)*, que quedará sujeta a los principios generales de la compra pública.

Sin embargo, si el mercado ya está preparado para dar respuesta a las necesidades planteadas en un plazo razonable de tiempo, la *Compra pública de tecnología innovadora (CPTI)*, mediante los procedimientos habituales abiertos o restringidos sin negociación, puede convertirse en adecuada.
Pero tenemos que poder prever el recurso del procedimiento de licitación con negociación o el de diálogo competitivo que nos pueden aportar soluciones finales comerciales innovadoras recién llegadas al mercado.

El diálogo competitivo ha demostrado ser útil en los casos en que los poderes adjudicadores no están en condiciones de definir los medios ideales para satisfacer sus necesidades o evaluar las soluciones técnicas, financieras o jurídicas que puede ofrecer el mercado.
Esta situación se puede presentar en cualquier contrato, pero, especialmente, en los proyectos innovadores, en la ejecución de grandes proyectos de infraestructuras de transporte integrado o en las redes o los proyectos informáticos de grandes dimensiones que requieran una financiación compleja y estructurada.

Además de los procedimientos ordinarios con o sin diálogo y negociación, las directivas de 2014 nos ofrecen un procedimiento nuevo y creado específico para la promoción de la innovación desde la demanda, *la asociación para la innovación*, un procedimiento que integra la posibilidad de investigación y contratación del primer piloto.

En el capítulo Procedimientos de esta guía presentamos el detalle de las diferentes alternativas con respecto a los procedimientos y su elección.

[TIP]
====
* Colaboración
* Compromiso
* Confianza
====

*Considerar y aprender a gestionar los riesgos*

La buena gestión de proyectos públicos siempre tiene que ir acompañada de un ejercicio de identificación y análisis de riesgos.
Se llevará a cabo durante la fase de planificación del proyecto y se repetirá durante las diferentes fases de la compra pública.
Para eso se tiene que implicar un amplio grupo de actores interesados tanto por la definición de las necesidades de compra como por el análisis de los riesgos.

Las nuevas reglas sobre contratación pretenden facilitar la cooperación entre autoridades contratantes, hecho que puede promover compartir riesgos y beneficios para abordar proyectos innovadores y agrupar la demanda.
Y es que la aversión al riesgo puede frenar los esfuerzos que se invierten en la promoción de la CPI desde el Ayuntamiento.

Muchos de los riesgos, aunque no todos, pue-den gestionarse con una elección adecuada del procedimiento de contratación, una estrategia de propiedad intelectual y unas cláusulas contractuales adecuadas.
Para reducir los riesgos asociados al desarrollo de CPI o de una compra pública pre-comercial (CPP), se tiene que desarrollar una estrategia que se anticipe a estos desafíos y permita una planificación y gestión adecuadas.
Se puede consultar a otras organizaciones o personas expertas que ya hayan desarrollado este tipo de procedimientos.
La Plataforma de la contratación de innovación proporciona un foro con este fin (ver más información en _https://www.innovation-procurement.org_).

Una vez identificados los riesgos hay varias maneras de gestionarlos:

*Tomar medidas que incidan en la probabilidad de que ocurra.*
Por ejemplo, una medida de reducir los riesgos en la entidad contratante misma es incluir un plan de contingencia para personas que vayan a gestionar el proyecto, como hacer una buena planificación y formarse en CPI.
Para reducir los riesgos tecnológicos, hay que dejar tiempo para poder probar la solución.
Para prevenir el hecho de quedarse con una única entidad proveedora, la solución será hacer una demanda conjunta para aumentar el volumen de adquisición y que resulte así más atractiva para el mercado, con más partes interesadas.

*Reparto o transferencia del riesgo entre las partes.*
Es aconsejable poner el riesgo en la parte que mejor puede controlarlo.
Los riesgos también pueden ser divididos en elementos que se puedan dividir entre las partes.

*Evitar acciones que aumenten los riesgos.*
Al acabar el proyecto, se hace un seguimiento de los riesgos para comprobar la veracidad de la probabilidad e impacto estimado.
De aquí se extraen las lecciones aprendidas que se utilizarán en proyectos futuros.

.Ejemplo de la ciudad de Detmold: hormigón fotocatalítico
[TIP]
Durante la Consulta al mercado se evaluaron los riesgos técnicos en relación con los estudios de investigación publicados y los datos de los fabricados.
Se organizaron visitas a las fábricas y se compararon los diferentes enfoques de los productos.
Se llevó a cabo un análisis de la sostenibilidad basándose en la estimación de una vida útil de al menos 50 años.
Se remitieron los resultados al equipo de planificación para que determinase qué técnicas eran las más apropiadas pera el proyecto.
Y se pidió la aprobación política pera el conjunto del trabajo teniendo en cuenta los costes adicionales estimados asociados al úso de hormigón fotocatalítico.

*Los derechos de propiedad intelectual*

La CPI implica invertir en hacer realidad nuevas ideas, tanto por parte de la autoridad con-tratante como por la de la empresa proveedora del producto o servicio.
Todas querrán maximizar su inversión, y eso se hace habitualmente en forma de derechos de propiedad intelectual e industrial (DPI).
El Ayuntamiento tiene que desarrollar una estrategia sobre DPI que tenga en cuenta los usos previsibles del producto o servicio que está comprando, a efectos de obtener los beneficios de la innovación más relevantes para ella.

Por ejemplo, si se desarrolla un nuevo diseño de contenedores de reciclaje dentro de un contrato de gestión de residuos, ¿qué es mejor para la administración: comprarlo o pagar una licencia de uso?
¿Y en el caso de los derechos sobre el diseño de los vehículos para la recogida de estos contenedores?
Al responder a estas preguntas, hay que tener en cuenta cuestiones como la capacidad futura de la Administración para cambiar de empresa proveedora, o hasta qué punto se podría dar licencia de este diseño a otro público usuario potencial del servicio.

En algunos casos, para alcanzar estos objetivos será suficiente compartir información sin una transferencia efectiva de derechos de propiedad intelectual y/o industrial.

*Financiación*

Tenemos que disponer de financiación para la compra inicial y hacer las previsiones para el escalado de la solución si la encontramos satisfactoria.

*Compras conjuntas*

Este nuevo modelo de relación contractual nos permite fomentar procedimientos de contratación más amplios y dinámicos, posibilitándonos plantear, incluso, procesos de compras conjuntas y de demanda agregada con otras administraciones.
Se tendrá que analizar caso por caso si las necesidades detectadas son adecuadas para una CPI conjunta, y si tiene o no sentido establecer un acuerdo marco de manera que otras administraciones puedan utilizar los resultados finales.

*La redacción de los pliegos de condiciones. Medidas para la innovación*

En la redacción de los pliegos de licitación para la adquisición de obras, bienes y servicios se incorporarán, de manera generalizada, medidas de potenciación de la innovación a partir de la fijación de prescripciones técnicas de carácter funcional, con criterios de adjudicación que potencien las mejoras articuladas como propuestas de innovación o cualquier otra medida que favorezca una innovación relacionada con el desarrollo de la sostenibilidad económica, social y ambiental.

¿Cómo podemos hacerlo?

* *Estableciendo prescripciones técnicas* que vayan en el camino de alcanzar los objetivos definidos.
Si las configuramos como obligatorias, querrá decir que el mercado las puede responder sin más preparativos.
Pero puede ser una prescripción técnica que restrinja el mercado porque es de materialización imposible en el tiempo de un periodo de presentación de proposiciones o, alternativamente, podemos dar tiempo para que el mercado se prepare: una vez más, destacamos la programación en la contratación pública.
También podemos indicar prescripciones técnicas “opcionales” o que representen mejoras voluntarias, que no hacen peligrar el resultado del concurso.
O podemos trasladar nuestros objetivos funcionales como prescripciones técnicas que no detallan como tiene que ser concretamente lo que queremos, sino cómo es lo que queremos.

* *Estableciendo criterios de solvencia técnica* que indiquen los medios técnicos y los procesos de calidad en los circuitos internos de las empresas que apunten que serán capaces de abordar ofertas con elementos de innovación.

* *Fijando criterios de adjudicación* que valoren las soluciones innovadoras, las nuevas ideas que den respuesta a los requerimientos de las prescripciones técnicas que ahora trasladaremos al mismo criterio de adjudicación: es el momento de puntuar y destacar las empresas que hacen el esfuerzo de superar sus ofertas rutinarias y demuestran que han estudiado nuestros retos y aportan soluciones: tecnológicas, organizativas, procedimentales o combinadas todas o algunas de estas, pero que suponen un compromiso de la empresa licitadora a satisfacer estos resultados.

* *Condicionando el precio a la incorporación de la innovación.*
Incorporar los resultados innovadores puede ser un incentivo económico en fase de ejecución del contrato, de manera que se pagará una parte del precio en función de la consecución de unos resultados que comprometen la incorporación de unos objetivos funcionales innovadores.

* Potenciando la *subcontratación especializada* por partes del objeto del contrato que requieren la participación de empresas emprendedoras especializadas.

Si lo que necesitamos no es tan solo una evolución renovadora de un contrato ordinario sino que se cree una auténtica alianza con empresas para desarrollar una nueva prestación, ya se trata ahora de constituir una “asociación para la innovación”.
El proyecto se formaliza como una colaboración público-privada para diseñar, producir y adquirir nuevos servicios, bienes o actividades inexistentes en el mercado.
Si se pretende abordar, es mejor que primeramente se contacte con la dirección de coordinación de contratación que ayudarán a diseñar el proyecto.

La valoración de las ofertas tiene que ser objetiva, motivada y razonable.
Por lo tanto, tenemos que diseñar los criterios de valoración, cuando se trate de criterios de adjudicación, y los tenemos que explicar claramente identificando los resultados requeridos de la manera más comprensible y concreta posible.

La innovación es una apuesta por el desarrollo sostenible en ayuda de la eficiencia en la prestación de los servicios públicos a la ciudadanía.
Pero no pueden ser las ocurrencias imaginativas imposibles de hacer.
Hay que traccionar el mercado y orientarlo hacia nuestras necesidades, no domesticar nuestras necesidades para las limitaciones u objetivos de rendimientos de beneficios a corto plazo de determinadas empresas.

== PILAR IV: seguir y evaluar

*La ejecución del contrato*

La fase de ejecución del contrato se vuelve esencial.
En ella se pondrán de manifiesto todos los procedimientos previos realizados y la buena tarea preparatoria.

Ahora bien, tenemos que entender firmemente que en estos procedimientos la contratación no acaba con la adjudicación, sino que tendremos que establecer un sistema de monitorización y control de la ejecución por parte de la empresa contratista, y gestionar la colaboración del Ayuntamiento con el contratista para la corrección del desarrollo del contrato.

*Eficiencia del contrato*

Un indicador útil para evaluar resultados es la eficiencia del contrato.
Tenemos que tener en cuenta en nuestros contratos el cociente de rendimiento entre las prestaciones obtenidas en relación con el precio que pagamos y si este se está cumpliendo o no.

También se efectuarán evaluaciones periódicas de resultados, en las partes que se considerarán sustanciales, entre otras:

* Si la innovación satisface la necesidad formulada al principio, respetando los criterios sociales y ambientales establecidos.
* Cuál es el valor añadido de la innovación en seguridad, funcionalidad y costes, y en eficiencia social.
* ¿Es la innovación adecuada para su implementación a gran escala?

En periodos más largos y establecidos, es conveniente que el Ayuntamiento evalúe la aplicación de la estrategia de política de CPI.
Hay que verificar si los objetivos se siguen y consiguen.
Por ejemplo, se evalúa si hay suficiente espacio para innovaciones en los contratos y cómo se están eliminando los obstáculos a la innovación.

*Escalado de la solución*

Es importante, una vez aplicada la solución, hacer una valoración objetiva de los resultados obtenidos y la viabilidad del escalado de la solución y el incremento del impacto previsto, así como su sostenibilidad.
