ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

= Cómo hacerlo realidad. Principios y procedimientos

== Cómo empezamos?

La contratación pública para la innovación no es un procedimiento de contratación nuevo, es una nueva manera de contratar de forma colaborativa para responder a necesidades que no encuentran solución en el mercado.

Esta manera de contratar con una visión estratégica nos lleva a una planificación más esmerada de nuestra acción de compra.
Es una nueva cultura.
Tenemos que reflexionar con una visión holística sobre todo el proceso, desde la detección de la necesidad, la consulta en el mercado o la preparación administrativa, hasta la ejecución; pero también observando el seguimiento y la evaluación de los resultados.
Tenemos que verificar en qué grado satisfacemos finalmente nuestras necesidades y podemos escalar las soluciones tal y como habíamos planificado.

.Algunas acciones a emprender

[TIP]
====
* Formación
* Planificación, colaboración y confianza
* Creación de redes
* Provisión de financiación
* Análisis de riesgos
* ... y “más formación”...
====

Cada compra tendrá que ser analizada caso por caso.
¿Qué necesidad tenemos que cubrir?
¿Existe ya la solución en el mercado o hay que inventarla?
¿Qué pasaría si, existiendo, todavía no estuviera comercializada...?
¿Nuestro proveedor se puede convertir en nuestro socio?

Por eso tenemos que estructurar nuestras compras en cuatro pilares.

[cols="^,^,^,^", , grid=cols, valign=top, options="header",]
|===
|Pilar I  |Pilar II |Pilar III |Pilar IV
|Detectar las necesidades
|Involucrar a los diferentes actores
|Iniciar la compra
|Seguir y evaluar
|Identificación del reto y de la compra para la  innovación con un impacto claro y escalable.
|Identificación de los actores, preparación de reuniones de trabajo, aviso previo de licitación,
consultas en el mercado y aseguramiento de la igual
dad de trato.
|Elección del procedimiento, redacción de los pliegos, establecimiento de los criterios de selección, gestión del riesgo, procesos de financiación...
Valorar compras conjuntas
|Seguimiento de la ejecución del contrato (el verdadero cambio)
Evaluación de la CPI y resumen de lecciones aprendidas
|===

Veámoslo paso a paso...

== PILAR I: Detectar las necesidades

Todas las personas nos encontramos ante multitudes de necesidades y problemas para resolver.
Tendríamos que definir con amplitud de miras los objetivos a alcanzar mediante el contrato público: detectar vuestros objetivos, vuestras necesidades y vuestros retos.
Hay que aplicar un sistema e ir construyendo un catálogo e inventario de estas necesidades.
Nos tenemos que plantear, una vez formuladas las necesidades, si están orientadas con los objetivos de la ciudad y la ciudadanía, si pueden ser solucionadas por procesos sencillos o tenemos que aplicar métodos complejos.
En definitiva, tenemos que construir una categorización y orden de prioridades.

*Empieza pronto y decide si estás ante una CPI*

El hecho de querer promover la innovación no tiene que llevarnos a crear falsas necesidades.
La detección de auténticas necesidades será el fruto de sesiones conjuntas de trabajo con los actores que trabajan con el bien o el servicio a comprar, con el personal técnico, las personas usuarias, los proveedores.
Estas sesiones se plantean como una lista de deseos a alcanzar.
Por eso, antes de hacer el pliego hay que averiguar si la solución existe o no y si necesita o no el desarrollo de pruebas piloto.

*Ejemplo:*

En el marco de proyectos CPI financiados bajo el programa FEDER RIS3cat, el reto que se está planteando el Ayuntamiento es la investigación de soluciones en pavimentos que reduzcan el efecto de isla de calor, la generación de ruido y la reducción de contaminación atmosférica.

De las sesiones internas de trabajo se ha entendido que los pavimentos urbanos tendrían que contribuir al hecho de que la ciudad fuera más confortable para sus habitantes, alcanzando un carácter más natural con características parecidas a la piel o a la ropa, y ser resistentes a las solicitaciones externas, permitiendo la transpirabilidad, el drenaje y el mantenimiento de una temperatura confortable.
La piel tiene terminaciones nerviosas (sensores) que permiten sentir frío o calor, o detectar patologías o daños con un cambio de color y otros (erupciones, cortes, etc.).
Estas han sido las bases para iniciar una consulta en el mercado y determinar si existen soluciones que den respuesta a esta necesidad.

.*Necesidades: la clave*
[TIP]
Una evaluación de necesidades debe tener en cuenta tanto las necesidades actuales como las futuras, y examinar la capacidad de la organización para asumir las soluciones potenciales.
Una evaluación de las necesidades genera una mejor base de consulta abierta al mercado, ya que proporciona datos esenciales para las entidades proveedoras e identifica cualquier tipo de laguna.

== PILAR II: Involucrar a los diferentes actores

Una vez hemos formulado nuestro reto, es fundamental contar con la ayuda de profesionales y un servicio de asesorías con conocimiento actualizado del mercado, y asegurarse una imagen completa de los últimos avances.
Para ello se tiene que consultar una amplia variedad de fuentes y trabajar con equipos multidisciplinares.
Podemos recurrir a otras gerencias o áreas de la misma organización, a congresos locales o internacionales, universidades, agencias de innovación y/o redes europeas, asociaciones empresariales, sindicales, sociales, vecinales, etc.
Tenemos que decidir qué información es necesaria recoger y compartir y a qué operadores del mercado nos tenemos que dirigir.

*Consultas en el mercado*

En el proceso de estructuración de nuestra compra también podemos formalizar una consulta en el mercado.
El lanzamiento de la consulta preliminar del mercado nos permitirá conocer la oferta existente y, al mismo tiempo, nos posibilitará implicar anticipadamente el mercado.

Estas consultas no son vinculantes para la Administración y, en ningún caso, no tienen que privilegiar a unos actores frente a otros, de manera que toda la información durante la consulta tiene que ser pública, se tienen que proteger los derechos de propiedad industrial e intelectual de las entidades proveedoras, y se tiene que informar de los resultados.
Este diálogo puede iniciarse con un anuncio previo de licitación.
Los pasos esenciales a seguir son los siguientes:

* Decidir qué información es necesario recoger y compartir, y a qué operadores de mercado hay que dirigirse.
* Escoger el mejor formato para la consulta y preparar los recursos materiales y humanos necesarios.
* Desarrollar la consulta conservando un archivo del desarrollo y asegurando la igualdad de trato.

*Evaluación de la sostenibilidad y la innovación en los resultados de la consulta en el mercado*

El Ayuntamiento está elaborando una metodología de apoyo para facilitar la evaluación de las ideas y las soluciones que nos lleguen de la consulta al mercado.
La metodología que se utiliza es general para cualquier idea o solución y permitirá priorizarlas según el grado de innovación y sostenibilidad que aporten.

El método tiene dos fases: en una primera, se evalúa la innovación que aporta la idea en sí misma y atendiendo a las circunstancias del entorno, de la entidad proponente y la alineación que la idea tiene con los objetivos del Ayuntamiento de Barcelona.

En una segunda fase hay que analizar la sostenibilidad de la idea a partir de analizar cómo es de real, viable y social su implementación.

.Caso SPEA EINDHOVEN - La palabra clave es ‘colaboración’
[TIP]
El ayuntamiento de Eindhoven apuesta por la construcción sostenible con un enfoque más integrado y holístico, un enfoque que haga lógico que las diferentes partes involucradas se esfuercen para la calidad a largo plazo y satisfagan las necesidades de todas las partes interesadas.
Además, las inversiones en innovación y calidad requieren un plazo más largo para obtener un rendimiento suficiente de la inversión gracias a las economías de escala y la cooperación.
El horizonte del proyecto es, por lo tanto, 2045.
La metodología de “Paso Natural” se aplica para mejorar la sostenibilidad de los edificios
_(http://www.eindhoven.nl/artikelen/Duurzaamheid-volgens-The-Natural-Step.htm)_
//enllaç trencat

== PILAR III: Iniciar la compra

*Elección del procedimiento: Los factores a considerar*

El primer paso para escoger el procedimiento es formularse las preguntas siguientes:
¿necesitaré una I+D+i?
¿Hay la solución pero no a escala comercial?
¿Disponemos de suficiente información para redactar las prescripciones técnicas?
Se recomienda un uso flexible de los procedimientos de contratación y una decisión caso por caso.

De hecho, podemos solucionar algunos de nuestros retos adquiriendo innovación mediante la introducción de *cláusulas o medidas de innovación en nuestras compras regulares*.

Si entendemos que hay que contratar exclusivamente servicios de I+D para desarrollar una solución que no está disponible en el merca-do, haremos uso de la *Compra pública pre-comercial (CPP)*, que quedará sujeta a los principios generales de la compra pública.

Sin embargo, si el mercado ya está preparado para dar respuesta a las necesidades planteadas en un plazo razonable de tiempo, la *Compra pública de tecnología innovadora (CPTI)*, mediante los procedimientos habituales abiertos o restringidos sin negociación, puede convertirse en adecuada.
Pero tenemos que poder prever el recurso del procedimiento de licitación con negociación o el de diálogo competitivo que nos pueden aportar soluciones finales comerciales innovadoras recién llegadas al mercado.

El diálogo competitivo ha demostrado ser útil en los casos en que los poderes adjudicadores no están en condiciones de definir los medios ideales para satisfacer sus necesidades o evaluar las soluciones técnicas, financieras o jurídicas que puede ofrecer el mercado.
Esta situación se puede presentar en cualquier contrato, pero, especialmente, en los proyectos innovadores, en la ejecución de grandes proyectos de infraestructuras de transporte integrado o en las redes o los proyectos informáticos de grandes dimensiones que requieran una financiación compleja y estructurada.

Además de los procedimientos ordinarios con o sin diálogo y negociación, las directivas de 2014 nos ofrecen un procedimiento nuevo y creado específico para la promoción de la innovación desde la demanda, *la asociación para la innovación*, un procedimiento que integra la posibilidad de investigación y contratación del primer piloto.

En el capítulo Procedimientos de esta guía presentamos el detalle de las diferentes alternativas con respecto a los procedimientos y su elección.

[TIP]
====
* Colaboración
* Compromiso
* Confianza
====

*Considerar y aprender a gestionar los riesgos*

La buena gestión de proyectos públicos siempre tiene que ir acompañada de un ejercicio de identificación y análisis de riesgos.
Se llevará a cabo durante la fase de planificación del proyecto y se repetirá durante las diferentes fases de la compra pública.
Para eso se tiene que implicar un amplio grupo de actores interesados tanto por la definición de las necesidades de compra como por el análisis de los riesgos.

Las nuevas reglas sobre contratación pretenden facilitar la cooperación entre autoridades contratantes, hecho que puede promover compartir riesgos y beneficios para abordar proyectos innovadores y agrupar la demanda.
Y es que la aversión al riesgo puede frenar los esfuerzos que se invierten en la promoción de la CPI desde el Ayuntamiento.

Muchos de los riesgos, aunque no todos, pue-den gestionarse con una elección adecuada del procedimiento de contratación, una estrategia de propiedad intelectual y unas cláusulas contractuales adecuadas.
Para reducir los riesgos asociados al desarrollo de CPI o de una compra pública pre-comercial (CPP), se tiene que desarrollar una estrategia que se anticipe a estos desafíos y permita una planificación y gestión adecuadas.
Se puede consultar a otras organizaciones o personas expertas que ya hayan desarrollado este tipo de procedimientos.
La Plataforma de la contratación de innovación proporciona un foro con este fin (ver más información en _https://www.innovation-procurement.org_).

Una vez identificados los riesgos hay varias maneras de gestionarlos:

*Tomar medidas que incidan en la probabilidad de que ocurra.*
Por ejemplo, una medida de reducir los riesgos en la entidad contratante misma es incluir un plan de contingencia para personas que vayan a gestionar el proyecto, como hacer una buena planificación y formarse en CPI.
Para reducir los riesgos tecnológicos, hay que dejar tiempo para poder probar la solución.
Para prevenir el hecho de quedarse con una única entidad proveedora, la solución será hacer una demanda conjunta para aumentar el volumen de adquisición y que resulte así más atractiva para el mercado, con más partes interesadas.

*Reparto o transferencia del riesgo entre las partes.*
Es aconsejable poner el riesgo en la parte que mejor puede controlarlo.
Los riesgos también pueden ser divididos en elementos que se puedan dividir entre las partes.

*Evitar acciones que aumenten los riesgos.*
Al acabar el proyecto, se hace un seguimiento de los riesgos para comprobar la veracidad de la probabilidad e impacto estimado.
De aquí se extraen las lecciones aprendidas que se utilizarán en proyectos futuros.

.Ejemplo de la ciudad de Detmold: hormigón fotocatalítico
[TIP]
Durante la Consulta al mercado se evaluaron los riesgos técnicos en relación con los estudios de investigación publicados y los datos de los fabricados.
Se organizaron visitas a las fábricas y se compararon los diferentes enfoques de los productos.
Se llevó a cabo un análisis de la sostenibilidad basándose en la estimación de una vida útil de al menos 50 años.
Se remitieron los resultados al equipo de planificación para que determinase qué técnicas eran las más apropiadas pera el proyecto.
Y se pidió la aprobación política pera el conjunto del trabajo teniendo en cuenta los costes adicionales estimados asociados al úso de hormigón fotocatalítico.

*INTELLECTUAL PROPERTY RIGHTS*

PPI implies investing in making new ideas a reality, both on the part of the contracting authority as well as the part of the company providing the product or service.
Everyone will want to maximise their investment, and this is generally done through intellectual and industrial property rights (IPR).
The City Council must develop a strategy for IPR which considers the foreseeable uses of the product or service it is buying, so as to obtain the most relevant benefits from the innovation.

For example, if a new design for recycling containers is developed within a waste management contract, what is better for the administration: to purchase the design or pay for a usage license?
And in the case of rights to the design for the vehicles that collect these containers?
When answering these questions, we must consider issues such as the Administration’s future capacity to change provider, or to what extent this design could be licensed to another potential group of users of the service.

In some cases, to achieve these objectives, it will be sufficient to exchange information without an effective transfer of intellectual and/or industrial property rights.

*FUNDING*

We must have funding available for the initial procurement and to make provisions for the scaling up the solution if we find it to be satisfactory.

*JOINT PROCUREMENT PROCESSES*

This new model for contractual relations allows us to promote broader and more dynamic procurement procedures, enabling us to even consider joint and aggregate demand procurement processes with other administrations.
We will have to analyse case by case whether the needs detected are ideally suited to a joint PPI, and whether it makes sense to establish a framework agreement so that other administrations can use the final results.

*DRAFTING SPECIFICATIONS. MEASURES FOR INNOVATION*

In general, when drafting the tender specifications for procuring works, goods and services, measures to strengthen innovation will be included through the establishing functional technical specifications, with award criteria that promote improvements articulated as innovation proposals or any other measure which promotes innovation related to developing economic, social and environmental sustainability.

How are we going to do this?

* *By establishing technical terms* that are aligned with achieving established objectives.
If we establish the terms as mandatory, this means that the market can respond to them without further preparations.
However, these technical terms could restrict the market because they are impossible to complete before the dead-line for submitting proposals; alternatively, we could give the market time to prepare: once again, we highlight the planning of public procurement.
We can also indicate “optional” technical terms, or terms which involve voluntary improvements, which do not put the result of the tender in danger.
We could also convey our functional objectives as technical terms that do not state specifically what we want, but rather describe the characteristics of what we want.

* *By establishing technical competence criteria* which set out the technical means and quality processes within companies that indicate that they will be capable of handling offers with elements of innovation.

* *By setting award criteria* that value innovative solutions, new ideas that offer a solution to the requirements of the technical terms, which now become the award criteria themselves.
This is the time to score and highlight the companies that make an effort to go beyond their ordinary offers and demonstrate that they have studied our challenges and which provide technological, organisational, or procedural solutions, or any combination thereof, and who show a commitment to satisfying those results.

* *By making the price conditional on the inclusion of innovation.*
Including innovative results can be an economic incentive in the contract execution phase, such that a part of the price will be paid depending on whether the company achieves results that involve the inclusion of innovative functional objectives.

* *By strengthening specialised outsourcing* for the parts of the contract that require the participation of specialised enterprising companies.

If what we need is not only innovative changes in an ordinary contract, but rather the creation of a true alliance of companies in order to develop a new service, this is now an “innovation partnership”.
The project is created as a public/private collaboration to design, produce and acquire new services, goods or activities which do not exist on the market.
If this type of association is going to be attempted, we recommend first getting in touch with the procurement coordination department, who will help you design the project.

The assessment of offers must be objective, grounded and reasonable.
Therefore, we must design the assessment criteria for awarding contracts, and we must explain them clearly, identifying the results required in the most understandable, specific form possible.

Innovation is a commitment to sustainable development in support of efficiency in providing public services to citizens.
However, they cannot be imaginative ideas that are impossible to implement.
We must drive the market and guide it towards our needs, not diminish our needs because of the short-term limitations or profit objectives of certain companies.

== PILLAR IV: monitor and assess

*CONTRACT EXECUTION*

The contract execution phase is essential.
Here, all of the prior procedures carried out and good preparatory work will become evident.

However, we must understand that in these procedures, procurement does not end with the award of contract.
Instead, we must establish a system to monitor and oversee execution by the contractor company and to manage collaboration between the City Council and the contractor to correctly implement the contract.

*CONTRACT EFFICIENCY*

A useful indicator to assess results is the efficiency of the contract.
We must bear in mind the performance quotient in our contracts between the performance obtained as compared to the price we pay, and whether this quotient is being met or not.

There will also be periodic assessments of results for elements considered to be substantial, such as:

* Whether the innovation satisfies the need posed at the beginning, while respecting established social and environmental criteria.
* What the added value of the innovation is in terms of security, functionality, costs and social efficiency.
* Can the innovation be implemented on a large scale?

For longer and more established terms, the City Council should also assess the application of the PPI policy strategy.
We must verify if the objectives are being followed and achieved.
For example, we can evaluate if there is enough room for innovation in the contracts and how barriers to innovation are being removed.

*SCALING THE SOLUTION*

Once the solution has been applied, it is important to carry out an objective assessment of the results obtained, the viability of scaling the solution and increasing the expected impact, as well as its sustainability.
