ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

= Cómo hacerlo realidad. Principios y procedimientos

== Cómo empezamos?

La contratación pública para la innovación no es un procedimiento de contratación nuevo, es una nueva manera de contratar de forma colaborativa para responder a necesidades que no encuentran solución en el mercado.

Esta manera de contratar con una visión estratégica nos lleva a una planificación más esmerada de nuestra acción de compra.
Es una nueva cultura.
Tenemos que reflexionar con una visión holística sobre todo el proceso, desde la detección de la necesidad, la consulta en el mercado o la preparación administrativa, hasta la ejecución; pero también observando el seguimiento y la evaluación de los resultados.
Tenemos que verificar en qué grado satisfacemos finalmente nuestras necesidades y podemos escalar las soluciones tal y como habíamos planificado.

.Algunas acciones a emprender

[TIP]
====
* Formación
* Planificación, colaboración y confianza
* Creación de redes
* Provisión de financiación
* Análisis de riesgos
* ... y “más formación”...
====

Cada compra tendrá que ser analizada caso por caso.
¿Qué necesidad tenemos que cubrir? ¿Existe ya la solución en el mercado o hay que inventarla? ¿Qué pasaría si, existiendo, todavía no estuviera comercializada...? ¿Nuestro proveedor se puede convertir en nuestro socio?

Por eso tenemos que estructurar nuestras compras en cuatro pilares.

[cols="^,^,^,^", , grid=cols, valign=top, options="header",]
|===
|Pilar I  |Pilar II |Pilar III |Pilar IV
|Detectar las necesidades
|Involucrar a los diferentes actores
|Iniciar la compra
|Seguir y evaluar
|Identificación del reto y de la compra para la  innovación con un impacto claro y escalable.
|Identificación de los actores, preparación de reuniones de trabajo, aviso previo de licitación,
consultas en el mercado y aseguramiento de la igual
dad de trato.
|Elección del procedimiento, redacción de los pliegos, establecimiento de los criterios de selección, gestión del riesgo, procesos de financiación...
Valorar compras conjuntas
|Seguimiento de la ejecución del contrato (el verdadero cambio)
Evaluación de la CPI y resumen de lecciones aprendidas
|===

Veámoslo paso a paso...

== PILAR I: Detectar las necesidades

Todas las personas nos encontramos ante multitudes de necesidades y problemas para resolver.
Tendríamos que definir con amplitud de miras los objetivos a alcanzar mediante el contrato público: detectar vuestros objetivos, vuestras necesidades y vuestros retos.
Hay que aplicar un sistema e ir construyendo un catálogo e inventario de estas necesidades.
Nos tenemos que plantear, una vez formuladas las necesidades, si están orientadas con los objetivos de la ciudad y la ciudadanía, si pueden ser solucionadas por procesos sencillos o tenemos que aplicar métodos complejos.
En definitiva, tenemos que construir una categorización y orden de prioridades.

*Empieza pronto y decide si estás ante una CPI*

El hecho de querer promover la innovación no tiene que llevarnos a crear falsas necesidades.
La detección de auténticas necesidades será el fruto de sesiones conjuntas de trabajo con los actores que trabajan con el bien o el servicio a comprar, con el personal técnico, las personas usuarias, los proveedores.
Estas sesiones se plantean como una lista de deseos a alcanzar.
Por eso, antes de hacer el pliego hay que averiguar si la solución existe o no y si necesita o no el desarrollo de pruebas piloto.

*Ejemplo:*

En el marco de proyectos CPI financiados bajo el programa FEDER RIS3cat, el reto que se está planteando el Ayuntamiento es la investigación de soluciones en pavimentos que reduzcan el efecto de isla de calor, la generación de ruido y la reducción de contaminación atmosférica.

De las sesiones internas de trabajo se ha entendido que los pavimentos urbanos tendrían que contribuir al hecho de que la ciudad fuera más confortable para sus habitantes, alcanzando un carácter más natural con características parecidas a la piel o a la ropa, y ser resistentes a las solicitaciones externas, permitiendo la transpirabilidad, el drenaje y el mantenimiento de una temperatura confortable.
La piel tiene terminaciones nerviosas (sensores) que permiten sentir frío o calor, o detectar patologías o daños con un cambio de color y otros (erupciones, cortes, etc.).
Estas han sido las bases para iniciar una consulta en el mercado y determinar si existen soluciones que den respuesta a esta necesidad.

.*Necesidades: la clave*
[TIP]
Una evaluación de necesidades debe tener en cuenta tanto las necesidades actuales como las futuras, y examinar la capacidad de la organización para asumir las soluciones potenciales.
Una evaluación de las necesidades genera una mejor base de consulta abierta al mercado, ya que proporciona datos esenciales para las entidades proveedoras e identifica cualquier tipo de laguna.

== PILAR II: Involucrar a los diferentes actores

Una vez hemos formulado nuestro reto, es fundamental contar con la ayuda de profesionales y un servicio de asesorías con conocimiento actualizado del mercado, y asegurarse una imagen completa de los últimos avances.
Para ello se tiene que consultar una amplia variedad de fuentes y trabajar con equipos multidisciplinares.
Podemos recurrir a otras gerencias o áreas de la misma organización, a congresos locales o internacionales, universidades, agencias de innovación y/o redes europeas, asociaciones empresariales, sindicales, sociales, vecinales, etc.
Tenemos que decidir qué información es necesaria recoger y compartir y a qué operadores del mercado nos tenemos que dirigir.

*Consultas en el mercado*

En el proceso de estructuración de nuestra compra también podemos formalizar una consulta en el mercado.
El lanzamiento de la consulta preliminar del mercado nos permitirá conocer la oferta existente y, al mismo tiempo, nos posibilitará implicar anticipadamente el mercado.

Estas consultas no son vinculantes para la Administración y, en ningún caso, no tienen que privilegiar a unos actores frente a otros, de manera que toda la información durante la consulta tiene que ser pública, se tienen que proteger los derechos de propiedad industrial e intelectual de las entidades proveedoras, y se tiene que informar de los resultados.
Este diálogo puede iniciarse con un anuncio previo de licitación.
Los pasos esenciales a seguir son los siguientes:

* Decidir qué información es necesario recoger y compartir, y a qué operadores de mercado hay que dirigirse.
* Escoger el mejor formato para la consulta y preparar los recursos materiales y humanos necesarios.
* Desarrollar la consulta conservando un archivo del desarrollo y asegurando la igualdad de trato.

*ASSESSMENT OF SUSTAINABILITY AND INNOVATION IN THE RESULTS OF THE MARKET CONSULTATION*

The City Council is developing a support methodology to facilitate the assessment of the ideas and solutions that we get from market consultations.
The methodology used applies to any idea or solution and will allow us to prioritise them according to the degree of innovation and sustainability they contribute.

The method has two phases: first, the innovation that the idea itself contributes is assessed, keeping in mind the circumstances of the environment, the proposing entity, and how well the idea aligns with the goals of Barcelona City Council.

The second phase analyses the sustainability of the idea based on an analysis of how realistic, viable and beneficial its implementation is.

.SPEA EINDHOVEN Case - The key word is “collaboration”
TIP: Eindhoven City Council made a commitment to sustainable construction with a more comprehensive, holistic approach, an approach which makes it logical for the different parties involved to make an effort to achieve long-term quality and to satisfy the needs of all parties.
Furthermore, investments in innovation and quality require a longer term to obtain a sufficient return on the investment thanks to economies of scale and cooperation.
The duration of the project, therefore, extends to 2045.
The “Natural Step” methodology is being applied to improve the sustainability of buildings
_(http://www.eindhoven.nl/artikelen/Duurzaamheid-volgens-The-Natural-Step.htm)_

== PILLAR III: Begin the procurement process

*CHOOSING THE PROCEDURE: FACTORS TO CONSIDER*

The first step in choosing the procedure is to ask the following questions:
Will I need Research, Development and Innovation?
Is there a solution, but not on a commercial scale?
Do we have enough information to draft the technical specifications?
We recommend a flexible use of procurement procedures and decisions made on a case-by-case basis.

In fact, we can solve some of our challenges by acquiring innovation through the addition of *innovation clauses or measures in our regular procurement processes.*

If we see that we must procure exclusively R&D services to develop a solution that is not available on the market, we will use a *Pre-commercial Public Procurement (PPP)* process, which will be subject to the general principles of public procurements.

However, if the market is already prepared to respond to the needs identified in a reasonable period of time, a *Public Procurement of* *Innovative Technology (PPIT)* process, using the normal open or restricted procedures without negotiation, may be suitable.
However, we have to be able to consider the use of an invitation to tender procedure with negotiation or a competitive dialogue process that will be able to provide us with innovative final commercial solutions that are new to the market.

Competitive dialogue has proven to be useful in cases in which the contracting entities are not in a position to define the ideal means of satisfying their needs or assess the technical, financial or legal solutions that the market may offer.
This situation may arise for any contract, but is particularly common with innovative projects, in the execution of large integrated transport infrastructure projects, or for large-scale networks or IT projects which require complex, structured funding.

In addition to the ordinary procedures with or without dialogue and negotiation, the 2014 directives offer us a new procedure that was created specifically to promote innovation from demand, *association for innovation*.
This procedure includes the possibility for performing research and procuring the first pilot.

The Procedures chapter of this guide presents more information on the different options with regard to procedures and how to choose one.

[TIP]
====
* Collaboration
* Commitment
* Trust
====

*CONSIDER AND LEARN TO MANAGE RISKS*

Proper management of public projects necessarily includes risk identification and analysis.
This step will be carried out during the project planning phase and will be repeated during the different phases of the public procurement process.
Therefore, a wide-ranging group of players must be involved both when defining the procurement needs as well as when analysing risk.

The new rules on procurement aim to facilitate cooperation between contracting authorities, which could encourage the sharing of risks and benefits to tackle innovative projects and group demand.
Risk aversion could slow the efforts being invested in promoting PPI at the City Council.

Many of the risks, although not all, can be managed with an appropriate choice of procurement procedure, an intellectual property strategy, and the appropriate contractual clauses.
To reduce the risks associated with PPI or with a precommercial public procurement (PPP), a strategy that anticipates these challenges and allows for the appropriate planning and management must be established.
Other organisations or experts who have developed these types of procedures may be consulted.
The innovation procurement platform provides a forum for this purpose (see more information at _https://www.innovation-procurement.org_).

Once the risks have been identified, there are several ways to manage them:

*Implement measures that reduce the likelihood of issues arising.*
For example, a way of reducing risks of the contracting entity is to include a contingency plan for the people who are going to manage the project, as well as properly plan the project and receive training on PPI.
To reduce technological risks, sufficient time must be allowed to test the solution.
To prevent getting stuck with just one supplier, the solution would be to create joint demand to increase acquisition volume, thereby increasing the appeal to the market, meaning there will be more entities interested.

*Division or transfer of risk among the parties.*
It is a good idea for risk to be put on the party that can best control it.
Risk can also be divided into elements that can be distributed among the parties.

*Avoid actions that increase risk.*
At the end of the project, a follow-up study of the risks will be carried out to verify the accuracy of the estimated likelihood and impact.
The lessons learned from this analysis will be used in future projects.

.Example from the city of Detmold: photocatalytic concrete
TIP: During the market consultation, the technical risks were assessed with regard to available research studies and manufacturer information.
Visits to the factories were organised and different approaches to the products were compared.
A sustainability analysis was carried out based on an estimation of a life span of at least 50 years.
The results were sent to the planning team to determine which techniques were the most appropriate for the project.
Finally, political approval was requested for all of the work, keeping in mind the additional estimated costs associated with the use of photocatalytic concrete.

*INTELLECTUAL PROPERTY RIGHTS*

PPI implies investing in making new ideas a reality, both on the part of the contracting authority as well as the part of the company providing the product or service.
Everyone will want to maximise their investment, and this is generally done through intellectual and industrial property rights (IPR).
The City Council must develop a strategy for IPR which considers the foreseeable uses of the product or service it is buying, so as to obtain the most relevant benefits from the innovation.

For example, if a new design for recycling containers is developed within a waste management contract, what is better for the administration: to purchase the design or pay for a usage license?
And in the case of rights to the design for the vehicles that collect these containers?
When answering these questions, we must consider issues such as the Administration’s future capacity to change provider, or to what extent this design could be licensed to another potential group of users of the service.

In some cases, to achieve these objectives, it will be sufficient to exchange information without an effective transfer of intellectual and/or industrial property rights.

*FUNDING*

We must have funding available for the initial procurement and to make provisions for the scaling up the solution if we find it to be satisfactory.

*JOINT PROCUREMENT PROCESSES*

This new model for contractual relations allows us to promote broader and more dynamic procurement procedures, enabling us to even consider joint and aggregate demand procurement processes with other administrations.
We will have to analyse case by case whether the needs detected are ideally suited to a joint PPI, and whether it makes sense to establish a framework agreement so that other administrations can use the final results.

*DRAFTING SPECIFICATIONS. MEASURES FOR INNOVATION*

In general, when drafting the tender specifications for procuring works, goods and services, measures to strengthen innovation will be included through the establishing functional technical specifications, with award criteria that promote improvements articulated as innovation proposals or any other measure which promotes innovation related to developing economic, social and environmental sustainability.

How are we going to do this?

* *By establishing technical terms* that are aligned with achieving established objectives.
If we establish the terms as mandatory, this means that the market can respond to them without further preparations.
However, these technical terms could restrict the market because they are impossible to complete before the dead-line for submitting proposals; alternatively, we could give the market time to prepare: once again, we highlight the planning of public procurement.
We can also indicate “optional” technical terms, or terms which involve voluntary improvements, which do not put the result of the tender in danger.
We could also convey our functional objectives as technical terms that do not state specifically what we want, but rather describe the characteristics of what we want.

* *By establishing technical competence criteria* which set out the technical means and quality processes within companies that indicate that they will be capable of handling offers with elements of innovation.

* *By setting award criteria* that value innovative solutions, new ideas that offer a solution to the requirements of the technical terms, which now become the award criteria themselves.
This is the time to score and highlight the companies that make an effort to go beyond their ordinary offers and demonstrate that they have studied our challenges and which provide technological, organisational, or procedural solutions, or any combination thereof, and who show a commitment to satisfying those results.

* *By making the price conditional on the inclusion of innovation.*
Including innovative results can be an economic incentive in the contract execution phase, such that a part of the price will be paid depending on whether the company achieves results that involve the inclusion of innovative functional objectives.

* *By strengthening specialised outsourcing* for the parts of the contract that require the participation of specialised enterprising companies.

If what we need is not only innovative changes in an ordinary contract, but rather the creation of a true alliance of companies in order to develop a new service, this is now an “innovation partnership”.
The project is created as a public/private collaboration to design, produce and acquire new services, goods or activities which do not exist on the market.
If this type of association is going to be attempted, we recommend first getting in touch with the procurement coordination department, who will help you design the project.

The assessment of offers must be objective, grounded and reasonable.
Therefore, we must design the assessment criteria for awarding contracts, and we must explain them clearly, identifying the results required in the most understandable, specific form possible.

Innovation is a commitment to sustainable development in support of efficiency in providing public services to citizens.
However, they cannot be imaginative ideas that are impossible to implement.
We must drive the market and guide it towards our needs, not diminish our needs because of the short-term limitations or profit objectives of certain companies.

== PILLAR IV: monitor and assess

*CONTRACT EXECUTION*

The contract execution phase is essential.
Here, all of the prior procedures carried out and good preparatory work will become evident.

However, we must understand that in these procedures, procurement does not end with the award of contract.
Instead, we must establish a system to monitor and oversee execution by the contractor company and to manage collaboration between the City Council and the contractor to correctly implement the contract.

*CONTRACT EFFICIENCY*

A useful indicator to assess results is the efficiency of the contract.
We must bear in mind the performance quotient in our contracts between the performance obtained as compared to the price we pay, and whether this quotient is being met or not.

There will also be periodic assessments of results for elements considered to be substantial, such as:

* Whether the innovation satisfies the need posed at the beginning, while respecting established social and environmental criteria.
* What the added value of the innovation is in terms of security, functionality, costs and social efficiency.
* Can the innovation be implemented on a large scale?

For longer and more established terms, the City Council should also assess the application of the PPI policy strategy.
We must verify if the objectives are being followed and achieved.
For example, we can evaluate if there is enough room for innovation in the contracts and how barriers to innovation are being removed.

*SCALING THE SOLUTION*

Once the solution has been applied, it is important to carry out an objective assessment of the results obtained, the viability of scaling the solution and increasing the expected impact, as well as its sustainability.
