ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

= Los procedimientos

== Los procedimientos regulares motores de la compra para la innovación

Dentro de la compra regular, la normativa de contratación pública de 2014 y la Ley de Contratos del Sector Público, ofrecen múltiples medios “propicios a la innovación”.

Destaca la posibilidad de llevar a cabo consultas preliminares del mercado.
La capacidad de tener en cuenta consideraciones ambientales y sociales en diferentes fases del proceso de contratación y el uso de cálculos del coste del ciclo de vida tienen una base jurídica más sólida.

Se pueden promover soluciones innovadoras a las cuales podemos dar más puntos viendo los beneficios económicos y de sostenibilidad que implican a largo plazo.
De la misma manera, la aplicación de especificaciones funcionales o basadas en los resultados dan más margen para las propuestas innovadoras.

Además, algunas modificaciones de los procedimientos de selección y los requisitos de documentación tienen como objetivo velar por la mejora del acceso de las pymes (muchas de las cuales son muy innovadoras) a los procedimientos de contratación pública.

Las nuevas normas de contratación conjunta transfronteriza permitirán que entidades compradoras de diversos estados miembros hagan compras conjuntas.
La agregación de la demanda de diversos estados miembros puede animar el reparto de riesgos y beneficios de los proyectos innovadores y el agrupamiento de la demanda.
Y, finalmente, lo que es quizás lo más importante: la aplicación de las nuevas normas europeas nos ofrece la oportunidad de evaluar la contratación pública desde un punto de vista estratégico y de averiguar la mejor manera de conseguir la innovación y otros objetivos.

A todo eso añadimos el aumento del apoyo de los sistemas electrónicos que comportan los avances hacia una contratación electrónica para fomentar la innovación en la contratación pública.

== Las directivas europeas

Más allá de los medios a utilizar en los procedimientos tradicionales, en la última reforma de las directivas europeas, se han revisado los procedimientos ya existentes y se han introducido algunas nuevas con el fin de dar apoyo a la innovación desde la demanda, como vemos a continuación.

En el ámbito de las directivas, hay procedimientos especialmente relevantes para la CPI:

*Diálogo competitivo*

Este procedimiento se ha simplificado en las nuevas normas.
Normalmente se utiliza en proyectos grandes y complejos en los cuales no se pueden definir anticipadamente las prescripciones técnicas.

Por ejemplo, cuándo los poderes adjudicadores no están en condiciones de definir los medios ideales para satisfacer sus necesidades o evaluar las soluciones que puede ofrecer el mercado.
Cuando las necesidades de la autoridad contratante no se puedan satisfacer sin adaptar las soluciones actualmente disponibles, o bien las necesidades implican diseño o soluciones innovadoras.
También cuando el contrato no pueda adjudicarse sin previa negociación por causa de la complejidad, la estructura legal o financiera, o por causa de los riesgos asociados a estas.

Las empresas licitadoras admitidas en el diálogo presentarán un documento descriptivo, y puede haber una o varias rondas de diálogo.
Las ideas generales se van concretando en esta fase de diálogo.
Cuando la autoridad cierre el diálogo, podrán presentar una oferta basada en su propia solución para las necesidades que la autoridad contratante ha definido.
En el procedimiento de diálogo competitivo, cualquier operador económico puede presentar una solicitud de participación, pero solo podrán participar en el diálogo en los operadores invitados.

*Procedimiento de licitación con negociación*

El objetivo, en este caso, es la contratación de obras, servicios o suministros que incluyan elementos de adaptación, diseño, innovación u otras características que hagan inadecuada la adjudicación del contrato sin previa negociación.
Al contrario que en el diálogo competitivo visto anteriormente, aquí es requisito previo que la autoridad contratante especifique desde un primer momento las características de los bienes o servicios a contratar.

Se puede utilizar en las mismas circunstancias, anteriormente descritas, que el diálogo competitivo, por ejemplo, cuando hacen falta adaptación, diseño o innovación, cuando el contrato no pueda ser adjudicado sin previa negociación a causa de riesgos o complejidad, cuando las prescripciones técnicas no pueden ser definidas con la precisión suficiente, o cuando solo se hayan presentado ofertas irregulares o inaceptables en un procedimiento previo.
Eso se ha introducido en las directivas de 2014, y sustituye el anterior procedimiento negociado con publicidad.

En el «procedimiento de licitación con negociación», cualquier operador económico puede presentar una solicitud de participación, pero solo los operadores económicos invitados tras la evaluación de la información proporcionada podrán presentar una oferta inicial, que será la base de las negociaciones posteriores.

*Se ha creado un nuevo procedimiento, la asociación para la innovación*

Es para los casos en que se requiera una solución innovadora que todavía no está disponible en el mercado.
El poder adjudicador decide establecer una asociación para la innovación con uno o varios actores, que efectúan por separado actividades de investigación y desarrollo, con la finalidad de negociar una nueva solución innovadora durante el procedimiento de licitación.

Finalmente, en casos y circunstancias específicas, los poderes adjudicadores podrán adjudicar contratos públicos mediante *un procedimiento negociado sin publicación previa de un anuncio de licitación.*

== Otros

Fuera del ámbito de las directivas hay un procedimiento que puede conducir a una compra pública de innovación.
Se trata de la contratación precomercial (CPP) y es la menos utilizada hasta ahora, pero tiene un gran potencial.
Si necesitamos contratar servicios de I+D, incluyendo las fases de creación de prototipos o las primeras pruebas de producción, este es el camino.

La CPP puede incluir la contratación de prototipos limitados y/o el desarrollo de pruebas de producto, pero no incluye la compra de grandes cantidades de soluciones finales en fase comercial, y tampoco tiene que constituir ayuda de Estado.
Por eso, el beneficio que se derive de los servicios de I+D contratados no será exclusivamente para el uso de la autoridad contratante.

.Thalea II
[TIP]
THALEA II es el primer CPI que sigue un CPP en Health-ICT para unidades de cuidados intensivos.
Participa, entre otros, la Corporación Sanitaria Parc Taulí de Sabadell.
Desplegará soluciones de teledetección y teleasistencia para mitigar los impactos negativos del envejecimiento de la sociedad y la mano de obra.
Haciendo balance de la experiencia adquirida a través del CPP de THALEA, mediante este CPI se adquirirá y desplegará una tecnología innovadora prometedora que ayudará a salvar más vidas y a aumentar la calidad de vida de los y las pacientes.
Más información: _www.thalea-pcp.eu_
