ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

= La estrategia de compra para la innovación

== La estrategia de compra para la innovación en el Ayuntamiento de Barcelona

El Ayuntamiento quiere participar en las ventajas de la compra para la innovación y se ha fijado como estrategia la introducción de una serie de acciones *para hacer que sus compras fomenten la innovación* con la finalidad de garantizar e incrementar el bienestar de las personas que viven en el territorio.

Si queremos promover un crecimiento sostenible e integrador en Barcelona, tenemos que aprender a utilizar todo el potencial que nos ofrece la normativa, teniendo en cuenta que en un tiempo breve habrá novedades, en particular, las novedades con respecto a CPI que introduce la directiva 2014/24.

Nos encontramos, por lo tanto, en un cambio de paradigma y de la cultura de la organización ante las compras.
Se nos abren las puertas a una nueva manera de contratar con claras ventajas que queremos incorporar lo antes posible.

El Ayuntamiento ha aprobado *normativa* como el decreto de contratación pública sostenible (S1/D/2017-1271 24/04) y las guías que lo desarrollan para impulsar las medidas sociales, éticas, ambientales y de innovación, y supone un punto de inflexión hacia esta nueva visión de las compras.

.La importancia de la consulta en el mercado
TIP: La ciudad de Detmold quería renovar la estación central de autobuses.
Identificó el potencial de reducir la contaminación mediante el uso de un hormigón fotocatalítico gracias a la información obtenida en la consulta del mercado: los pliegos especificaron que el hormigón debería tener entre un 3% y un 5% de TiO2 para una reducción anual en las emisiones de óxido de nitrógeno, en vez de una lista detallada de insumos.

Otras acciones que tiene previsto llevar a cabo el Ayuntamiento son las siguientes:

*Planificar las compras.*
Conviene tener en cuenta que la CPI es un nuevo instrumento para llegar a alcanzar nuestros objetivos de ciudad.
Es por eso que se tiene que hacer uso de la CPI en los casos en los que no existe la solución que necesitamos (o no a gran escala) y cuando dispondremos de un presupuesto de compra importante a aplicar a medio o largo plazo que garantice la escalabilidad de las soluciones.
Se tendrá que analizar caso por caso qué áreas se tienen que implicar en la CPI y cuál está mejor situada en la organización para liderar el proceso.

Este nuevo modelo de relación contractual nos permite fomentar procedimientos de contratación y ejecución de contratos más amplios y dinámicos posibilitándonos plantear, incluso, procesos de compras y ejecución conjuntas y de demanda agregada con otras administraciones.
Se tendrá que analizar caso por caso si las necesidades detectadas son adecuadas para una CPI conjunta, y si tiene o no sentido establecer un acuerdo marco de manera que otras administraciones puedan utilizar los resultados finales.

.Trabajo en red
[TIP]
====
* Integración de equipos multidisciplinares.
* Trabajo en red con la industria y las universidades.
* Redes de colaboración y de reparto de experiencias.
* Formación de personas formadoras.
====

*Determinar las áreas del consistorio más adecuadas para iniciar una CPI.*
La finalidad es empezar en el camino de las compras en las áreas que pueden tener más impacto o son más susceptibles de incorporar innovación, y después compartir los aprendizajes con el resto de áreas y regularizar el uso de la CPI.
Algunas áreas priorizadas son las TIC, la economía circular o la salud.

.Selección de áreas prioritarias
[TIP]
====
* Contratos marco
* Cálculo de rendimiento
* La tecnología como aliada
* Nuevos mecanismos de financiación
* Asesoramiento en todas las fases
====

*Dialogar con el mercado y el tejido empresarial.*
El marco legal actual recoge la posibilidad de iniciar un diálogo entre los poderes adjudicadores y el mercado, previo al inicio del expediente de contratación.
El Ayuntamiento habilitará los canales adecuados, principalmente digitales para establecer el diálogo.
El objetivo es conocer y hacer prospección de las soluciones que ofrece el mercado para cubrir las necesidades objeto del contrato antes de la publicación del pliego definitivo.
Eso permite una mejor y más profunda comprensión de las necesidades de la Administración, la promoción e incorporación de las últimas innovaciones existentes en el mercado y una colaboración mayor entre las partes.

.Gestión estratégica a medio y largo plazo
[TIP]
====
* Estrategias de compras diferenciadas
* Equipos especializados
* Análisis del coste del ciclo de vida
* Gestión de riesgos
* Evaluación de resultados
* Control de calidad
* Derechos de propiedad intelectual
====

*Introducir medidas de innovación en cada contrato.*
La lógica de esta idea es que la innovación no es algo estático o algo de lo que se pueda planificar la aparición.
Por lo tanto, el consistorio se plantea trabajar orientado a la innovación en sus contratos, llevar a cabo consultas de mercado y aumentar el diálogo con la industria.
Se trata de animar a investigadores, investigadoras y empresas a reflexionar sobre los retos de la ciudad, el bien-estar de las personas, y desarrollar soluciones innovadoras, incluso plantear compras centralizadas antes de que se haya lanzado un procedimiento de contratación.

*La tecnología como aliada.*
La evolución de las TIC y el uso general de internet están transformando prácticamente todos los sectores de la sociedad y de nuestra economía.
La información y los datos se han convertido en uno de los bienes más valiosos y preciados, y configuran lo que denominamos _economía del conocimiento o economía digital._

Las ciudades como Barcelona, con iniciativas como el Plan Barcelona Ciudad Digital 2017-2020, se enfrentan a la necesidad de transformar sus maneras de hacer y buscar nuevas estrategias basadas en la tecnología y la innovación que permitan aprovechar el impulso y el desarrollo de esta nueva economía y que comporten al mismo tiempo grandes beneficios sociales y un crecimiento económico más equitativo y sostenible.

Las medidas que habrá que observar y que impulsarán el nuevo modelo de contratación sostenible para la innovación se tendrán que estructurar en ejes de actuación como la ética de los datos o la soberanía tecnológica basada en _software libre_, datos abiertos y metodologías _ágiles_, que se desarrollarán en detalle en la futura guía de compra de tecnología del Ayuntamiento, actualmente en redacción.

*Habilitar fondos de financiación.*
El Ayuntamiento dispone de varios fondos para la financiación de sus proyectos CPI.
Uno de los más importantes es el mismo presupuesto de compras ordinarias, en el que, incorporando las medidas para la innovación, se convierte en uno de los ejes tractores más importantes.
El Ayuntamiento dispone también de fondos estructurales (FEDER) para apoyar a este proceso, y los quiere aplicar apoyar a las TIC, la economía circular y la salud.

También se pueden encontrar fondos de financiación en los provenientes por concurso de la UE, el Banco Mundial y otros para PYMES.
Desde diferentes organismos internacionales se está facilitando asesoramiento, apoyo financiero, organizando acontecimientos y convocando premios para ayudar a las autoridades contratantes a desarrollar CPI de manera abierta y no discriminatoria facilitando el acceso de las pequeñas y medianas empresas.

*Transmitir formación y conocimiento.*
Cada equipo de compra pública tendrá que identificar qué compras son objeto del procedimiento CPI y que, por lo tanto, necesitarán nuevas técnicas y conocimientos para detectar la innovación.
Esta innovación se puede encontrar de diferentes maneras, añadiendo nuevas tecnologías a nuestras adquisiciones, también solicitando bienes que sean la composición de producto y servicio o bien introduciendo nuevas maneras de fabricación de un mismo producto; en definitiva, serán necesarias nuevas habilidades en estos equipos para orientar los nuevos procesos de compra.

*Seleccionar periódicamente iniciativas modelo y hacer divulgación.*
Hay un delicado equilibrio entre el deber de asegurarse que el mercado conoce exactamente cuáles son los requerimientos públicos en una compra y al mismo tiempo dejar espacio suficiente para formas diferentes y nuevas de responder a estos requerimientos.
Se actuará con iniciativas para las cuales el Ayuntamiento cree que puede tener un papel demostrativo, con prescripciones técnicas funcionales basadas en el rendimiento, o permitiendo variantes, dos maneras interesantes de permitir cierta flexibilidad a las empresas licitadoras a la hora de proponer soluciones.

image::ict-procurement-pag12-{lang}.svg[image, align="center", width=100%]

== Las claves del éxito

Del estudio de benchmark realizado a nivel europeo por el Ayuntamiento se concluye que la promoción de la CPI debe ir idealmente acompañada de medidas de planificación y organización que facilitan el éxito de su implementación. Estas recomendaciones se pueden resumir en las 4M´s:

.Las claves del éxito: las cuatro emes (M)
[TIP]
====
* *Mandato político* al más alto nivel, con planificación de las compras a largo plazo y con equipos profesionales y estables.
* *Mentalidad:* Formación de los equipos, diálogo abierto y flexible con el mercado, cultura favorable promovida transversalmente.
* *Medios* y recursos humanos profesionales, expertos en gestión de riesgo con práctica en la evaluación de proyectos, formación y mecanismo de comunicación de buenas prácticas.
* *Medición.* Objetivos obligatorios y cuantificables, vinculantes y monitorizados.
====
